const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
const {build}=require('../../synthesis.js');
let errors;
test.beforeEach(async({page})=>{errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#moduleCount')).toHaveText('43');});
test.afterEach(()=>expect(errors).toEqual([]));
async function importText(page,data){await page.locator('#aiImportBtn').click();await page.locator('#importText').fill(typeof data==='string'?data:JSON.stringify(data));await page.locator('#applyImportBtn').click();}
async function exportData(page){await page.locator('.menu summary').click();const promise=page.waitForEvent('download');await page.locator('#saveBtn').click();const download=await promise;return JSON.parse(fs.readFileSync(await download.path(),'utf8'));}
async function at(page,x,y,action='click'){const point=await page.evaluate(({x,y})=>{const b=document.getElementById('board').getBoundingClientRect();const z=Number(document.getElementById('zoomSelect').value);return{x:b.x+x*z,y:b.y+y*z};},{x,y});await page.mouse[action](point.x,point.y);}
test('half-adder truth table, signals and dark theme',async({page})=>{await page.locator('#tab-analysis').click();await page.locator('#truthBtn').click();const rows=page.locator('#truthInfo tbody tr');await expect(rows).toHaveCount(4);for(const [i,want]of [[0,['0','0','0','0']],[1,['0','1','1','0']],[2,['1','0','1','0']],[3,['1','1','0','1']]])expect(await rows.nth(i).locator('td').allTextContents()).toEqual(want);await page.locator('#themeBtn').click();await expect(page.locator('body')).toHaveClass(/theme-dark/);await at(page,166,153,'dblclick');const data=await exportData(page);expect(data.components.find(c=>c.type==='switch').state.on).toBe(false);});
test('invalid import leaves current project and history intact',async({page})=>{const before=await exportData(page);await importText(page,{components:[{id:'m1',type:'not',x:10,y:10}],wires:[{id:'w2',from:{cid:'m1',pid:'bad'},to:{cid:'m1',pid:'a'}}]});await expect(page.locator('#importError')).toBeVisible();await expect(page.locator('#undoBtn')).toBeDisabled();await page.locator('#importDialog button[aria-label="Закрыть"]').click();expect((await exportData(page)).components).toEqual(before.components);});
test('Markdown import, export, undo and autosave restore',async({page})=>{const data=build('Y = A NAND B');data.title='ИИ отчёт';data.description='<img src=x onerror=alert(1)>';await importText(page,'Отчёт\n```json\n'+JSON.stringify(data)+'\n```');await expect(page.locator('#importDialog')).not.toBeVisible();await expect(page.locator('#projectTitle')).toHaveValue('ИИ отчёт');await expect(page.locator('#reportText')).toHaveText(data.description);await expect(page.locator('#reportText img')).toHaveCount(0);await page.locator('#undoBtn').click();await expect(page.locator('#projectTitle')).toHaveValue('Полусумматор');await page.locator('#redoBtn').click();await exportData(page);await page.reload();await expect(page.locator('#projectTitle')).toHaveValue('ИИ отчёт');});
test('formula builds a working shared half adder',async({page})=>{await page.locator('#tab-analysis').click();await page.locator('#expressionText').fill('S = A ^ B\nC = A & B');await page.locator('#synthesizeBtn').click();await expect(page.locator('#projectTitle')).toHaveValue('Схема из формул');await page.locator('#truthBtn').click();await expect(page.locator('#truthInfo tbody tr')).toHaveCount(4);expect(await page.locator('#truthInfo tbody tr').last().locator('td').allTextContents()).toEqual(['1','1','0','1']);});
test('bus connection connects all four bits and is undoable',async({page})=>{await importText(page,{title:'Bus',components:[{id:'m1',type:'input',x:80,y:80,props:{bitWidth:4},state:{value:9}},{id:'m2',type:'probe',x:600,y:80,props:{bitWidth:4}}],wires:[]});await page.locator('#busMode').check();await page.locator('#wireTool').click();await at(page,224,103.2);await at(page,592,103.2);await expect(page.locator('#boardSummary')).toContainText('4 соединений');const data=await exportData(page);expect(data.wires).toHaveLength(4);expect(data.wires.map(w=>w.from.pid)).toEqual(['out0','out1','out2','out3']);await page.locator('#undoBtn').click();await expect(page.locator('#boardSummary')).toContainText('0 соединений');});
test('properties keep input focus during simulation and Delete edits value',async({page})=>{await page.locator('#moduleSearch').fill('числовой вход');await page.locator('[data-type="input"]').click();await page.locator('#propValue').fill('11');await page.waitForTimeout(350);await expect(page.locator('#propValue')).toBeFocused();await page.locator('#propValue').press('Tab');const data=await exportData(page);expect(data.components.find(c=>c.type==='input').state.value).toBe(11);await page.locator('#propBitWidth').focus();await page.locator('#propBitWidth').press('Delete');await page.locator('#propBitWidth').fill('8');await page.locator('#propBitWidth').press('Tab');expect((await exportData(page)).components.find(c=>c.type==='input').props.bitWidth).toBe(8);});
test('subcircuit creation survives project export and reload',async({page})=>{await importText(page,{title:'Reusable AND',components:[{id:'m1',type:'and',x:200,y:150}],wires:[]});await at(page,246,190);page.once('dialog',d=>d.accept('Мой AND'));await page.locator('#createCustomBtn').click();await expect(page.locator('[data-type^="custom_"]')).toHaveCount(1);const data=await exportData(page);expect(data.customDefs[0].table['11'].o0).toBe('1');await page.reload();await expect(page.locator('[data-type^="custom_"]')).toHaveCount(1);await page.locator('[data-type^="custom_"]').click();expect((await exportData(page)).components.filter(c=>c.type.startsWith('custom_'))).toHaveLength(1);});
test('timing recorder exports changing signals',async({page})=>{await page.locator('#tab-analysis').click();await page.locator('#traceBtn').click();await at(page,166,153,'dblclick');await expect(page.locator('#traceInfo svg')).toHaveCount(1);await page.locator('#traceBtn').click();const promise=page.waitForEvent('download');await page.locator('#traceExportBtn').click();const data=fs.readFileSync(await (await promise).path(),'utf8');expect(data).toContain('ms');expect(data.split('\n').length).toBeGreaterThan(2);});
test('PNG is a real image and canvas memory stays bounded at 200%',async({page})=>{await page.locator('#zoomSelect').selectOption('2');expect(await page.locator('#board').evaluate(c=>c.width*c.height)).toBeLessThanOrEqual(16_000_000);await page.locator('.menu summary').click();const promise=page.waitForEvent('download');await page.locator('#exportPngBtn').click();const file=fs.readFileSync(await (await promise).path());expect([...file.subarray(0,8)]).toEqual([137,80,78,71,13,10,26,10]);});
test('mobile surface has accessible controls without page overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await expect(page.locator('#aiImportBtn')).toBeVisible();await expect(page.locator('#wireTool')).toBeVisible();for(const selector of ['.palette','.workspace-wrap','.inspector','#tickBtn','#fitBtn']){const box=await page.locator(selector).boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(391);}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.local/mobile.png',fullPage:true});});
test('subcircuit editing updates the definition and undo restores it',async({page})=>{await importText(page,{title:'Parent',components:[{id:'m1',type:'and',x:200,y:150}],wires:[]});await at(page,246,190);page.once('dialog',d=>d.accept('AND block'));await page.locator('#createCustomBtn').click();await page.locator('[data-type^="custom_"]').click();await page.locator('#openSubcircuitBtn').click();await expect(page.locator('#projectTitle')).toHaveValue('AND block');await at(page,246,190);await page.locator('#propOrientation').selectOption('south');await page.locator('#backToProject').click();await expect(page.locator('#projectTitle')).toHaveValue('Parent');let d=await exportData(page);expect(d.customDefs[0].source.components[0].props.orientation).toBe('south');await page.locator('#undoBtn').click();d=await exportData(page);expect(d.customDefs[0].source.components[0].props.orientation).toBeUndefined();expect(d.components.filter(c=>c.type.startsWith('custom_'))).toHaveLength(1);});

test('wheel zoom anchors the pointer while palette wheel keeps scrolling',async({page})=>{const zoom=page.locator('#zoomSelect');await zoom.selectOption('1');const box=await page.locator('#boardViewport').boundingBox(),x=box.x+350,y=box.y+250;const world=()=>page.evaluate(({x,y})=>{const b=document.getElementById('board').getBoundingClientRect(),z=Number(document.getElementById('zoomSelect').value);return [(x-b.x)/z,(y-b.y)/z];},{x,y});await page.mouse.move(x,y);const before=await world();await page.mouse.wheel(0,-100);await expect(zoom).toHaveValue('1.25');const after=await world();expect(Math.abs(before[0]-after[0])).toBeLessThan(2);expect(Math.abs(before[1]-after[1])).toBeLessThan(2);const palette=await page.locator('.palette-list').boundingBox();await page.mouse.move(palette.x+50,palette.y+100);await page.mouse.wheel(0,500);await expect.poll(()=>page.locator('.palette-list').evaluate(e=>e.scrollTop)).toBeGreaterThan(0);await expect(zoom).toHaveValue('1.25');});

test('code editor live preview, reverse conversion and safe invalid edits',async({page})=>{await page.locator('#aiImportBtn').click();await expect(page.locator('#importText')).toHaveValue(/switch m1/);await page.locator('#codeExampleBtn').click();await expect(page.locator('#codeStatus')).toContainText('6 блоков');await page.locator('#importText').fill('circuit "From code"\nswitch A(on=true)\nnot N\nindicator O\nA.out -> N.a\nN.y -> O.in');await expect(page.locator('#codeStatus')).toContainText('3 блоков');await expect(page.locator('#codePreview > svg')).toHaveCount(1);await page.locator('#importText').press('Control+Enter');await expect(page.locator('#projectTitle')).toHaveValue('From code');const p=await exportData(page);expect(p.components.map(c=>c.type)).toEqual(['switch','not','indicator']);await page.locator('#aiImportBtn').click();await expect(page.locator('#importText')).toHaveValue(/N.y -> O.in/);const codeDownload=page.waitForEvent('download');await page.locator('#importText').press('Control+s');expect((await codeDownload).suggestedFilename()).toBe('circuit.logic');await page.locator('#importText').fill('switch A\nA.out -> unknown.in');await expect(page.locator('#importError')).toContainText('Строка 2');await page.locator('#applyImportBtn').click();await expect(page.locator('#projectTitle')).toHaveValue('From code');await page.locator('#importDialog button[aria-label="Закрыть"]').click();expect((await exportData(page)).components).toEqual(p.components);});

test('theme palette and custom colors survive reload',async({page})=>{await page.locator('#appearanceBtn').click();await page.locator('#themePreset').selectOption('ocean');await expect(page.locator('body')).toHaveClass(/theme-dark/);await page.locator('#theme-accent').fill('#abcdef');await expect.poll(()=>page.locator('body').evaluate(e=>e.style.getPropertyValue('--accent'))).toBe('#abcdef');await page.locator('#themeDialog button[aria-label="Закрыть"]').click();await page.reload();await expect(page.locator('body')).toHaveClass(/theme-dark/);expect(await page.locator('body').evaluate(e=>e.style.getPropertyValue('--accent'))).toBe('#abcdef');await page.locator('#appearanceBtn').click();await page.locator('#themeResetBtn').click();expect(await page.locator('#theme-accent').inputValue()).toBe('#72b8dc');});

const simpleWire={title:'Cut',components:[{id:'A',type:'switch',x:100,y:100,state:{on:true}},{id:'O',type:'indicator',x:600,y:100}],wires:[{id:'wire',from:{cid:'A',pid:'out'},to:{cid:'O',pid:'in'},color:'#247a70'}]};
test('accidental wire selections and unfinished connections can always be cancelled',async({page})=>{await importText(page,simpleWire);await at(page,300,134);await expect(page.locator('#resetWireRoute')).toBeVisible();await page.locator('#propWireColor').focus();await page.keyboard.press('Escape');await expect(page.locator('#resetWireRoute')).toHaveCount(0);await at(page,300,134);await at(page,400,350);await expect(page.locator('#resetWireRoute')).toHaveCount(0);await page.locator('#wireTool').click();await at(page,192,134);await at(page,400,350);await expect(page.locator('#statusText')).toContainText('сброшены');await at(page,192,134);await page.mouse.click(500,500,{button:'right'});await expect(page.locator('#statusText')).toContainText('сброшены');await at(page,192,134);await at(page,192,134);await expect(page.locator('#statusText')).toContainText('сброшены');expect((await exportData(page)).wires).toHaveLength(1);});

test('scissors split a live connection, reconnecting and undo restore the signal',async({page})=>{await importText(page,simpleWire);await page.locator('#cutTool').click();await at(page,300,134);await expect(page.locator('#statusText')).toContainText('разделён');const cut=await exportData(page),contacts=cut.components.filter(c=>c.type==='contact');expect(contacts).toHaveLength(2);expect(cut.wires).toHaveLength(2);await page.locator('#tab-analysis').click();await page.locator('#truthBtn').click();expect(await page.locator('#truthInfo tbody tr').first().locator('td').allTextContents()).toContain('Z');await page.locator('#wireTool').click();await at(page,contacts[0].x+20,contacts[0].y+10);await at(page,contacts[1].x,contacts[1].y+10);await page.locator('#truthBtn').click();expect(await page.locator('#truthInfo tbody tr').first().locator('td').allTextContents()).not.toContain('Z');await page.locator('#undoBtn').click();expect((await exportData(page)).wires).toHaveLength(2);await page.locator('#undoBtn').click();const restored=await exportData(page);expect(restored.components).toHaveLength(2);expect(restored.wires).toHaveLength(1);});
